#!/usr/bin/env python

"""
slackd.slackd
~~~~~~~~~~~~~

:copyright: (c) 2016 David M. Westerhoff
:license: All rights reserved

"""

from __future__ import absolute_import
import click
from commands.search import search
from commands.open import open
from commands.status import status
from commands.users import users
from commands.channels import channels


# Root Command
# ~~~~~~~~~~~~
@click.group()
def slackd():
    pass


# Command Manifest
# ~~~~~~~~~~~~~~~~
slackd.add_command(open)
slackd.add_command(status)
slackd.add_command(users)
slackd.add_command(channels)
slackd.add_command(search)


# Run Script
# ~~~~~~~~~~
if __name__ == '__main__':
    slackd()
